server:
  port: 3333
  servlet:
    context-path: /api/v1

spring:
  application:
    name: cosplaystore
  datasource:
    url: jdbc:mysql://localhost:3306/cosplaystore
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
